### ISSUE TITLE
Implement `ProjectTile` component

### ISSUE THREAD

**Issue by sofiaromorales** [setlife-network/setlife-solutions#116]
https://www.figma.com/file/KlLr27PTO7Dzz3D9CE2LzT/setlife-core?node-id=1226%3A5706

**Comment by sofiaromorales** [comment]
<img width="375" alt="Free Mockup Scene copy 1" src="https://user-images.githubusercontent.com/49292858/184520232-416851cc-9eb5-4f56-ba4b-450579da88c8.png">

**Comment by Ovifer13** [comment]
Blocked by #119
