### ISSUE TITLE
Fix BitcoinBanner

### ISSUE THREAD

**Issue by Ovifer13** [setlife-network/setlife-solutions#123]
**How It looks**
![image](https://user-images.githubusercontent.com/86666889/185175724-53e92155-5aa5-4cf2-b562-55c996f4c86f.png)
![image](https://user-images.githubusercontent.com/86666889/185175822-8c4a8254-7d07-4e5e-8eaf-c9d57cb3fa3c.png)

**How It should look**
![image](https://user-images.githubusercontent.com/86666889/185175860-a7b628dd-a711-47c4-8c28-4639a786dfc5.png)
![image](https://user-images.githubusercontent.com/86666889/185175904-59b00a49-9513-42cf-a744-2b1decd199b0.png)

**Comment by otech47** [comment]
@Ovifer13 can you also use this link for the Learn More button: 

https://amber.app/blog/bitcoin-makes-sense-for-small-business/

Should open in a new tab
