### ISSUE TITLE
Replicate `Services` component in `Services` page

### ISSUE THREAD

**Issue by sofiaromorales** [setlife-network/setlife-solutions#148]

**Comment by Ovifer13** [comment]
@sofiaromorales is just to show this when you click the services option in the nav?
![image](https://user-images.githubusercontent.com/86666889/186760889-36cc773c-a6fc-4ea0-978b-bfaef5285f58.png)

**Comment by sofiaromorales** [comment]
@Ovifer13 yes, is to render the `Services` component but in the `ServicesPage`
