### ISSUE TITLE
Research requirements and processes for selling services to federal, state, and municipal organizations 

### ISSUE THREAD

**Issue by otech47** [setlife-network/setlife-solutions#18]
- Blocked until January 2020 due to minimum 2-year operational history

There may be other requirements

https://sam.gov/content/entity-registration

**Comment by ctrocc** [comment]
**Registering for Federal Contracts**

States appear to have a separate registration [process](https://www.dms.myflorida.com/content/download/148429/990692/Doing_Business_with_the_State_of_Florida_Overview.pdf)
Information to have Ready 
- [ ] DUNS Number 
- [ ] entity type 
- [ ] TIN (taxpayer identification number) and taxpayer name: TIN is either your SSN or SetLife's [EIN](https://www.irs-ein-tax-id.com/?utm_source=google&utm_medium=cpc&utm_campaign=main-ein&utm_term=federal%20ein&utm_content=b&gclid=Cj0KCQiAoNWOBhCwARIsAAiHnEgGNH3cqrIWBhqZTq_WmUaLK_SgQXGCknIzd8n9GbR0UoGru7jdtl4aAtpoEALw_wcB) 
- [ ] [CAGE (contractor and government entity) code ](https://federal.famr.us/CAGE-code/?utm_source=google&utm_medium=cpc&utm_campaign=186805600&utm_content=117927691336&utm_term=cage%20code&gclid=Cj0KCQiAoNWOBhCwARIsAAiHnEhQeDyVODzzan_80Fv-qw6aLKDRhUOjyzm9rnbpLSzH9EyLjCZL5soaAq-NEALw_wcB)
- [ ] banking information to set up EFT (electronic funds transfer) 
- [ ] Entering Assertions Section: info about goods and services we provide 
- [ ] EDI (electronic data interchange) information section 
- [ ] FAR (federal acquisitions regulation) responses questionnaire 
- [ ]  Architect and Engineering responses section  
- [ ] SBS supplemental page 
Once we're ready to register
- [ ] make a login.gov account 
- [ ] identity verification (state ID, SSN, and phone number/phone plane in your name (or will send you a mailed verification code in 3-5 days)

**Comment by ctrocc** [comment]
Local governments do not appear to require SAM, instead their process is simpler but annoying because there doesn't seem to be a standardized way to register us for all of these RFPs. For example Ft. Lauderdale and [Broward](https://www.broward.org/Purchasing/Pages/Registration.aspx) use a service called BidSync/Periscope 2SG.

**Comment by ctrocc** [comment]
**State of Florida**

- [ ] [Register](https://dos.myflorida.com/sunbiz/) with FL Dept of State, Division of Corporations 
- [ ] Register with [Florida Vendor Information Portal](https://vendor.myfloridamarketplace.com/vms-web/spring/login?execution=e1s1) (tax ID required, Federal EIN preferred) 
- [ ] Choose commodity codes 
- [ ] Get notifications of business opportunities

**Comment by ctrocc** [comment]
**Municipal Governments**

So far seems to use Periscope or Demandstar. 

Demandstar ones often require a separate registration with the municipality itself. These municipalities may ask for the following. 

- [ ] FEIN 
- [ ] W9
- [ ] DUNS
- [ ] Commodity Codes (unique to the municipality) 
- [ ] Other: All links to full requirements are found on the Slack Civics and Tech channel

**Comment by otech47** [comment]
Lookin goood 👍🏼 

See if you can get us registered on DemandStar (interested in Sunrise & Davie) and then we maybe we can start evaluating the quality of RFPs to see if it's worth going this route before even trying the GSA route which I expect will take many months before we can actually close a good bid

**Comment by otech47** [comment]
Lookin goood 👍🏼 

See if you can get us registered on DemandStar (interested in Sunrise & Davie) and then we maybe we can start evaluating the quality of RFPs to see if it's worth going this route before even trying the GSA route which I expect will take many months before we can actually close a good bid

**Comment by ctrocc** [comment]
Periscope, DemandStar, and GovSpend accounts are all set up

**Comment by otech47** [comment]
From looking at the 2 bid documents you've found so far (both look great in terms of relevance of the work) we will have to

- purchase insurance
- register with DOH e-verify system

**Comment by ctrocc** [comment]
I'll look into getting e-verified for now then.

**Comment by ctrocc** [comment]
I believe the insurance is only required after we are awarded the contact, but something we're going to have to get to eventually.

**Comment by ctrocc** [comment]
We should also look into getting MBE and CBA certified if we are not already.

**Comment by ctrocc** [comment]
Registered with EVerify. Log in information should be sent to directors@setlife.network soon.

**Comment by ctrocc** [comment]
All registered to do business with the State of Florida as a byproduct of the MBE process

**Comment by ctrocc** [comment]
Getting MBE Registered

- [ ] Register on MyFloridaMarketPlace
- [ ] Gather Required Documentation 
      - [ ] test

**Comment by ctrocc** [comment]
**Requirements for PBSC Bid Proposal**
- [ ] Register with PBDC
- [ ] Packet 
- [ ] Figure out wormholes
- [ ] Gather Required [Documentation](https://www.dms.myflorida.com/agency_administration/office_of_supplier_diversity_osd/get_certified/certification_required_documents) 
    - [ ] Submit *

**Comment by ctrocc** [comment]
**PBDC Bid Proposal Submission Task List**
- [ ] Register as vendor 
- [ ] Assemble Bid Proposal Package 
  - [ ] Cover Letter 
  - [ ] Project Experience 
  - [ ] Technical Requirements 
  - [ ] Proposed Project Team 
  - [ ] Methodology/Timeline 
  - [ ] Refrences 
  - [ ] Cost
  - [ ] Woman/Veteran/Minority Certification 
  - [ ] E-Verify Employment Eligibility Certification Affidavit 
  - [ ] Drug-Free Workplace Form 
  - [ ] Non-Collusion Affidavit
  - [ ] Proposal Certification 
- [ ] Submit through DemandStar by February 8th, 2022 @ 2 PM 

**If Bid Is Awarded To Us**
- [ ] Supply a Certificate of Insurance 
- [ ] W9 Taxpayer Form
- [ ] Submittal of Intent to Perform (just our quotation would be fine)

**Comment by ctrocc** [comment]
**JAX Bid Proposal Submission Task List** 

- [ ] Register as a vendor
- [ ] Assemble Bid Proposal Package (One original and one copy) 
  - [ ] Signed Bid Form 
  - [ ] Bid Proposal Form 
  - [ ] Conflict of Interest 
  - [ ] Requirements 
  - [ ] Addendums 
  - [ ] Buy American Preference Compliance Form 
    - [ ] Supporting documentation that at least 51% of what we offer in bid response is manufactured, produced, or assembled in the US (unsure of how relevant this is to us) 
  - [ ] Any licenses required by local, state, or federal laws
  - [ ] Mail to address by Jan 26th, 2022
- [ ] Insurance is required within 10 days of bid award

**Comment by otech47** [comment]
ready to close this now that we have opened new issues @ctrocc
