### ISSUE TITLE
Fix hamburger menu positioning

### ISSUE THREAD

**Issue by sofiaromorales** [setlife-network/setlife-solutions#218]
https://user-images.githubusercontent.com/49292858/191552023-bc8f76be-bd54-4ee4-96e4-f9f27194bfaa.mov

**Comment by sofiaromorales** [comment]
@Ovifer13 are you working on this? if so, do you need any help?

**Comment by Ovifer13** [comment]
@sofiaromorales Everything is almost done, I was trying to hide the scroll bar but everything I tried doesn't works, leet me do the PR so you can check it
