### ISSUE TITLE
URL search bug

### ISSUE THREAD

**Issue by daaveed** [setlife-network/setlife-solutions#226]
Typing "setlife.solutions" into browser (for the first time) does not reach the landing page of Setlife Solutions. Tested in Firefox and Google Chrome on PC, and Google Chrome on Apple iPad OS. Have to type "www" to reach site for the first time.

Once a user has reached the site via "www.setlife.solutions" and the site has been recorded in the browser history, then simply typing "setlife.solutions" will prompt the recognized Setlife Solutions site, and the "www" is not needed.

**Chrome on PC screenshots attached:**

![image](https://user-images.githubusercontent.com/41223034/192166139-7bcbfbdf-3f4a-4139-8bf5-f78e3c4f295b.png)

![image](https://user-images.githubusercontent.com/41223034/192166158-fa824ec5-0852-40fd-aa4a-acb8365524a7.png)

**Comment by otech47** [comment]
fixed via AWS
