### ISSUE TITLE
Implement testimonials model

### ISSUE THREAD

**Issue by sofiaromorales** [setlife-network/setlife-solutions#237]
1. Create migration with DB model
`testimonials`
- id
- person_name
- company_name
- testimony
- person_image_url
- company_image_url

2. Create API models and query
3. Create inserts for adding data into the tables

**Comment by otech47** [comment]
@Ovifer13 @sofiaromorales can you guys fix this problem: https://github.com/setlife-network/setlife-solutions/pull/238/files#r1018166242

it is blocking the frontend work

**Comment by otech47** [comment]
once this is fixed @vdegandesa can finish the frontend Testimonials section

**Comment by otech47** [comment]
feel free to keep this issue closed and re-open a new one if that's easier to track @Ovifer13 @sofiaromorales
