### ISSUE TITLE
Fix "Schedule Consultation" button

### ISSUE THREAD

**Issue by daaveed** [setlife-network/setlife-solutions#270]
Schedule consultation button: only text works as link to Form, empty space between text and button border inactive.

**Comment by otech47** [comment]
ok so this failed to deploy let's figure out why and open a new Pull Request @daaveed 

![Screenshot 2023-08-22 at 8 16 52 PM](https://github.com/setlife-network/setlife-solutions/assets/4914611/c84adc95-c077-4980-8227-1fe57bfd289a)

could you also help here @Ovifer13 

to test we should be able to run these commands without errors

```
npm install
npm run build
```
