### ISSUE TITLE
Establish code foundations for frontend and backend

### ISSUE THREAD

**Issue by otech47** [setlife-network/setlife-solutions#37]
Review existing code foundations and decide on architecture

- PostgreSQL for any DB functionalities
- React for frontend
- Styling library?
- Backend framework (Node/Express)
- https://node-postgres.com/
- https://sequelize.org/
- https://www.graphile.org/postgraphile/

**Comment by vdegandesa** [comment]
To all the team members.

- I would like to here your opinions about using Typescript for this project.
- I think it is becoming popular but I wouldn't know the pros and cons by using it.

**Comment by sofiaromorales** [comment]
![ER BDII 2 0 (1)](https://user-images.githubusercontent.com/49292858/174526121-0fd3e5bf-c7ef-44ef-b195-a72630d973e5.png)

**Comment by otech47** [comment]
ORM = https://sequelize.org/docs/v6/
