### ISSUE TITLE
Implement routes for each page

### ISSUE THREAD

**Issue by otech47** [setlife-network/setlife-solutions#40]
- `/` (root) => `HomePage`
- `/consultation` => `ConsultationPage`
- `/service-packages` => `ServicePackagesPage`
- `/projects` => `ProjectsPage`
- `/projects/:projectId` => `ProjectDetailPage`
- `/services/:serviceId` => `ServiceDetailPage`
- `/contributor-inquiry` => `ContributorInquiryPage`

**Comment by sofiaromorales** [comment]
Closed in https://github.com/setlife-network/setlife-solutions/pull/59
