### ISSUE TITLE
Implement ContributorInquiryPage component

### ISSUE THREAD

**Issue by otech47** [setlife-network/setlife-solutions#47]

**Comment by Ovifer13** [comment]
@otech47 https://www.figma.com/file/KlLr27PTO7Dzz3D9CE2LzT/setlife-core?node-id=1285%3A8026 Is this a button?

**Comment by otech47** [comment]
is what a button? your link shows me this:

![Screen Shot 2022-09-15 at 5 59 38 PM](https://user-images.githubusercontent.com/4914611/190516312-31985cc9-45aa-476c-a085-388d662ae35e.png)

**Comment by Ovifer13** [comment]
@otech47 In the LinkedIn input, I don't really know how that input works.
This is how it looks like before linking
![image](https://user-images.githubusercontent.com/86666889/190516512-e9b3d832-1e11-465e-9f84-db67b6888716.png)

After linking, it looks like this
![image](https://user-images.githubusercontent.com/86666889/190516580-fd911552-1503-4048-9dbf-6b1dd0079a0a.png)

**Comment by otech47** [comment]
@stefanny1mc can you help clarify?

I think check mobile design as well it might help

**Comment by Ovifer13** [comment]
It does the same in mobile

**Comment by otech47** [comment]
to me it looks like it should be a text field like the email and it is meant so the user can type a link to their personal website/github/portfolio/etc

**Comment by stefanny1mc** [comment]
that is a field to enter your linked in. when you enter it, it turns blue

**Comment by otech47** [comment]
let's just make it a normal text field for now that seems a bit confusing for the user

Make the placeholder text for that field: **Link to your work (Github, LinkedIn, portfolio, etc)**
