### ISSUE TITLE
Implement NavigationBar

### ISSUE THREAD

**Issue by otech47** [setlife-network/setlife-solutions#48]

**Comment by sofiaromorales** [comment]
@Ovifer13 this is a good place to start with the UI

![Screen Shot 2022-08-03 at 9 14 21 AM](https://user-images.githubusercontent.com/49292858/182616740-ee1d6c47-2b7f-4470-a6f2-3fa4533824d9.png)

**Comment by sofiaromorales** [comment]
This should be rendered for all the routes

**Comment by sofiaromorales** [comment]
https://nextjs.org/docs/basic-features/layouts
