### ISSUE TITLE
Implement `Footer` component

### ISSUE THREAD

**Issue by otech47** [setlife-network/setlife-solutions#49]
https://www.figma.com/file/KlLr27PTO7Dzz3D9CE2LzT/setlife-core?node-id=1160%3A6248

**Comment by sofiaromorales** [comment]
![Screen Shot 2022-08-03 at 9 15 45 AM](https://user-images.githubusercontent.com/49292858/182617038-7abff235-1f7d-4466-a983-ea5d6ceb149e.png)

**Comment by sofiaromorales** [comment]
This should be rendered for all the routes as a template

**Comment by sofiaromorales** [comment]
https://nextjs.org/docs/basic-features/layouts

**Comment by Ovifer13** [comment]
Blocked by #48

**Comment by otech47** [comment]
https://twitter.com/SetLifeLearning
https://www.youtube.com/channel/UCjyzH2XN7qB3WuWTPFbJXCQ
