### ISSUE TITLE
Create data model

### ISSUE THREAD

**Issue by otech47** [setlife-network/setlife-solutions#50]
- Services
- Service Packages
- Projects
- ProvidedServices (Service - Project relations)

**Comment by sofiaromorales** [comment]
![ER BDII 2 0 (3)](https://user-images.githubusercontent.com/49292858/174529348-184183e7-91d7-4dbe-857b-254eb64539b7.png)

**Comment by otech47** [comment]
tables for:

- inquiries
- consultation_requests

**Comment by otech47** [comment]
ServicePackage
- name (string)
- description (string)
- estimated_cost (string)
- minimum_cost (string)
- meeting_frequency (string)
- subtitle (string)
- additional_notice (string)
